### PR TITLE
v2.0

### PR DESCRIPTION
**Pull request by athaeryn**
It's time to release a new version of spaceBase!

The changelog has this to say:

- Replace media-query() mixin with media() mixin.
- Remove support for IE6/7.
- Remove dependency on Compass.
- Move island, lists and media partials into UI folder.
- Update to Normalize.css 3.0.3.
- Documentation!

Let's look at some of the changes in more detail.

# New `media` mixin

We've removed the `media-query` mixin in favor of a new, more flexible mixin named `media`. There's more to love about the new mixin than saving a few characters. In spaceBase v1, breakpoints were specified this way in `_vars.scss`:

```scss
// Breakpoints
// Set to false to exclude breakpoints
$hand-start:   480px;
$lap-start:    768px;
$desk-start:   1024px;
$wall-start:   1200px;
```

The first change with the new mixin was changing the structure of these settings:

```scss
// Breakpoints
$media-breakpoints: (
  hand: 480px,
  lap:  768px,
  desk: 1024px,
  wall: 1200px
);
```

The greatest benefit of this change is that we can iterate through each breakpoint in this list to generate things like the responsive visibility helpers. For instance, if you added `banana-phone: 500px` to the list, spaceBase will automatically generate the classes `.hidden-below-banana-phone` and `.hidden-banana-phone-and-up` for you to use. The same thing applies to the responsive push/pull classes and grid widths (e.g. `.banana-phone-five-eighths`). This change makes adding new breakpoints (and removing the ones you don't need) much easier and more powerful.

It's also possible to specify ranges. With `media-query`, you were limited to applying styles from a breakpoint and up, or up to (but not including) a breakpoint; you couldn't mix the two. With the new mixin you can do this:

```scss
@include media($from: lap, $upto: wall) { /*...*/ }
```

You can also specify custom media features. For example:

```scss
@include media('(device-radius: 50%)') { /*...*/ }
```

# Compass no longer required

It's no longer necessary to use a library like Compass or Bourbon to compile spaceBase. We've removed mixins provided by these, so we recommend using a tool like [autoprefixer](https://github.com/postcss/autoprefixer) to add vendor prefixes for browsers you need to support.

You can still use Compass if you'd like to, but it's no longer a requirement.

# Documentation

Finally, we've added a lot more documentation to spaceBase.

### CODE REVIEW

**Comment by cstoobes** [comment]
+1 !

**Comment by mckennedy** [comment]
+1!

**Comment by JonnyTee81** [comment]
+1!

**Comment by 99wesley99** [comment]
I love it!

**Comment by thorsonmscott** [comment]
"yum"

On Friday, October 9, 2015, Wesley Walz <notifications@github.com> wrote:

> I love it!
> On Oct 9, 2015 3:05 PM, "Jonny" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > +1!
> >
> > On Fri, Oct 9, 2015 at 2:59 PM, Mike Kennedy <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> > > +1!
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/space150/spaceBase/pull/56#issuecomment-146973542
> >.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/space150/spaceBase/pull/56#issuecomment-146974525>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/space150/spaceBase/pull/56#issuecomment-147012001>.
>


-- 


Max Thorson | thorsonmscott.com
Phone: 612-598-4277 | Email: max@thorsonmscott.com
Twitter: @thorsonmscott | Skype: thorsonmscott

**Pull request merged**
