### PR TITLE
switching up the styleguide color swatches.

### PR DESCRIPTION
**Pull request by mckennedy**
Changes to vars are immediately reflected when viewing in browser. label variables remain selectable.

### CODE REVIEW

**Comment by cstoobes** [comment]
Great idea!  Could the SCSS be simplified with a list of color names and @each function?

**Comment by mckennedy** [comment]
I'd imagine so. I don't know how. I'll look into that.

**Comment by athaeryn** [comment]
If `$all-colors` is just for the styleguide, could we rename it to `$styleguide-colors` (or maybe even move it to `styleguide.scss`)? Users that don't know what it's for may feel compelled to keep it up-to-date even if they're not using the styleguide.

Digging this though, nice work!

👍

**Comment by cstoobes** [comment]
I agree with Manderson on the name `$styleguide-colors`.

Also, instead of using `.sg-colors li:nth-of-type(...)` can you use the color name instead?  That way the order of swatches in the styleguide are not dependent on the order in the list. Plus you added all those classnames to the layout, but they aren't getting used anywhere.  :)

**Comment by mckennedy** [comment]
I like the renaming to $styleguide-colors. I'm not sure about moving it to styleguide.scss. You make a good point for users who don't know what it's for. I think it's nice to be able to reference the theme colors directly when adding to the $styleguide-colors list. What does everyone else think on that one? @cstoobes I'll check that out! Good call on the classes still being there yet unnecessary!

**Comment by athaeryn** [comment]
Yeah, renaming to `$styleguide-colors` but keeping it in vars sounds good to me.

**Comment by mckennedy** [comment]
After some discussion with @athaeryn, here's what I've come up with:

1. I removed that unnecessary classes.
2. I kept the for loop as an each loop requires I put classes on the swatches and a user still has to manually adjust the sg-label content to match order anyway. I wanted to keep the sg-label content selectable and having it dynamically populate in a :before or :after removes that ability.  

@each $color in $styleguide-colors {
  $i: index($styleguide-colors, $color);
  .sg-swatch-#{$i} {
    background: $color;
    &:after {
      content: "#{nth($styleguide-colors, $i)}"
    }
  }
}

**Comment by mckennedy** [comment]
you could also do something like this: https://codepen.io/robynlarsen/pen/Antwv

if you really want to make the colors list look like:

$colors-list: (midnight, $midnight), (steam, $steam), (snow, $snow), (cotton-rose, $cotton-rose), ("cabernet", $cabernet), (jade, $jade), (deep-sea, $deep-sea), ("aqua", $aqua)

**Pull request merged**
