### PR TITLE
4.0: No longer supporting legacy browsers (and other updates)

### PR DESCRIPTION
**Pull request by cstoobes**
Version 4.0 is long overdue! Here's the changelog (along with the flexbox grid in the other PR):

* Remove support for IE8/9.
* Update form styles.
* Update to Normalize.css 8.0.0.

### Remove support for IE8/9
We're dropping support for older versions of IE and with it the $legacy-ie variable. _manifest.scss and application-ie.scss are no longer necessary as there is now just one application.css for all. Documentation is updated to reflect this.

### Update form styles
Various updates to form controls for better cross-browser styling, pulled from Bootstrap. Also added their "form-group" to wrap labels and inputs.

### CODE REVIEW

**Comment by cstoobes** [comment]
Another update: Removed the rem conversion function because it's unnecessary since we no longer need pixel fallbacks to support legacy browsers.

Can I get some thumbs up from you guys? :)

**Comment by mckennedy** [comment]
you can.  👍

**Comment by tjdunklee** [comment]
👍 - Looks all good to me. Nice work!

**Comment by athaeryn** [comment]
👍

**Pull request merged**
